import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Terms and Conditions | Clutch Picks",
  description: "Terms and Conditions for using the Clutch Picks application.",
};

export default function TermsPage() {
  return (
    <main>
      <Navbar />

      <section className="pt-32 pb-20 px-6">
        <div className="max-w-3xl mx-auto">
          <h1
            className="text-4xl sm:text-5xl tracking-wider mb-2"
            style={{ fontFamily: "var(--font-heading)" }}
          >
            Terms and Conditions
          </h1>
          <p className="text-sm text-[var(--color-text-muted)] mb-12">
            Last Updated: March 2026
          </p>

          <div className="space-y-10 text-[var(--color-text-muted)] leading-relaxed text-sm sm:text-base">
            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                1. Acceptance of Terms
              </h2>
              <p>
                By downloading, installing, or using the Clutch Picks application
                (&quot;App&quot;), you agree to be bound by these Terms and Conditions. If
                you do not agree to these terms, please do not use the App.
              </p>
            </div>

            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                2. Entertainment Purpose Only
              </h2>
              <p>
                This App is intended for entertainment and informational purposes only.
                All predictions, picks, and analysis provided are opinions generated by
                AI and statistical models. They should not be relied upon as advice of
                any kind. Clutch Picks does not facilitate, encourage, or enable gambling
                or wagering of any kind.
              </p>
            </div>

            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                3. No Guarantee of Accuracy
              </h2>
              <p>
                We make no guarantees regarding the accuracy, reliability, or
                completeness of any predictions, analysis, or information provided.
                Sports outcomes are inherently unpredictable. Past results do not
                guarantee future performance.
              </p>
            </div>

            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                4. User Responsibility
              </h2>
              <p>
                Users are solely responsible for their own decisions and actions. You
                must comply with all applicable laws in your jurisdiction. This App does
                not facilitate or encourage illegal activities.
              </p>
            </div>

            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                5. No Liability
              </h2>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE APP, ITS CREATORS, OWNERS,
                OPERATORS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT,
                INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM
                YOUR USE OF THE APP OR ANY INFORMATION PROVIDED BY THE APP.
              </p>
            </div>

            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                6. Age Requirement
              </h2>
              <p>
                You must be at least 13 years of age to use this App. By using this App,
                you confirm that you meet this requirement.
              </p>
            </div>

            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                7. Subscription Terms
              </h2>
              <p className="mb-3">
                Clutch Picks offers an optional auto-renewable subscription (Clutch Pro)
                that provides access to AI predictions, confidence ratings, and detailed
                game analysis.
              </p>
              <p className="mb-3">
                Payment is charged to your Apple ID account at confirmation of purchase.
                The subscription automatically renews unless canceled at least 24 hours
                before the end of the current billing period. Your account will be
                charged for renewal within 24 hours prior to the end of the current
                period at the same price.
              </p>
              <p className="mb-3">
                You can manage and cancel your subscription in your device Settings under
                your Apple ID, then Subscriptions. Cancellation takes effect at the end
                of the current billing period. No refunds are provided for partial
                billing periods.
              </p>
              <p>
                Current pricing: $4.99 per month. Prices may vary by region and are
                subject to change.
              </p>
            </div>

            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                8. Indemnification
              </h2>
              <p>
                You agree to indemnify and hold harmless the App, its owners, developers,
                employees, and affiliates from any claims, damages, losses, or expenses
                arising from your use of the App or violation of these Terms.
              </p>
            </div>

            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                9. Changes to Terms
              </h2>
              <p>
                We reserve the right to modify these Terms at any time. Continued use of
                the App after changes constitutes acceptance of the modified Terms.
              </p>
            </div>

            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                10. Governing Law
              </h2>
              <p>
                These Terms shall be governed by and construed in accordance with the
                laws of the State of Mississippi, without regard to conflict of law
                principles.
              </p>
            </div>

            <div>
              <h2 className="text-lg text-white font-semibold mb-3">
                11. Contact
              </h2>
              <p>
                If you have questions about these Terms, contact us at{" "}
                <a
                  href="mailto:support@clutchpicksapp.com"
                  className="text-[var(--color-coral)] hover:underline"
                >
                  support@clutchpicksapp.com
                </a>
                .
              </p>
            </div>

            <div className="mt-12 pt-8 border-t border-white/10">
              <h2 className="text-lg text-white font-semibold mb-3">
                DISCLAIMER
              </h2>
              <p>
                By using Clutch Picks, you acknowledge that all predictions and analysis
                are for entertainment purposes only. You accept full responsibility for
                your own decisions. The App bears no liability for any outcomes resulting
                from your use of this service.
              </p>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
